# Generated by Django 3.0.4 on 2020-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200521_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
