# Generated by Django 3.0.4 on 2020-05-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200521_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
