# Generated by Django 3.0.4 on 2020-06-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_images_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
