# Generated by Django 3.0.4 on 2020-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
