# Generated by Django 3.0.4 on 2020-06-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200610_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
